# Generated by Django 2.2.9 on 2021-07-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210729_0047'),
        ('posts', '0003_auto_20210729_0024'),
    ]

    operations = [
    ]
